name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - head

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install current LMDB tools
      run: bundle exec rake lmdb_tools
    - name: Run specs with fresh LMDB dump samples
      run: bundle exec rake spec:create_fixtures spec
